# Generated by Django 5.2.1 on 2026-08-27 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitado_internacion', models.BooleanField(default=False, verbose_name='¿Capacitado Internación?')),
                ('formulario_capacitacion', models.CharField(blank=True, max_length=120, null=True, verbose_name='Formulario de Capacitación')),
                ('tipo_usuario', models.CharField(choices=[('MEDICO', 'Médico/a'), ('ENFERMERIA', 'Enfermería'), ('ADMINISTRATIVO', 'Administrativo/a'), ('OTRO', 'Otro Profesional')], max_length=30, verbose_name='Tipo de Usuario')),
                ('tiene_acceso_sigehos', models.BooleanField(default=False, verbose_name='¿Tiene acceso a SIGEHOS?')),
                ('trabaja_otro_hospital', models.BooleanField(default=False, verbose_name='¿Trabaja en otro hospital?')),
                ('permisos_solicitar', models.CharField(help_text='Ej: HIS NT - PROFESIONAL MEDICO', max_length=200)),
                ('id_agm_solicitado', models.CharField(blank=True, max_length=60, null=True, verbose_name='ID AGM Solicitado')),
                ('acceso_modulos_internacion', models.BooleanField(default=False, verbose_name='Acceso a Módulos de Internación')),
                ('apellido', models.CharField(max_length=80)),
                ('otro_apellido', models.CharField(blank=True, max_length=80, null=True)),
                ('nombre', models.CharField(max_length=80)),
                ('otro_nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('cuil', models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El CUIL debe contener exactamente 11 dígitos numéricos sin guiones ni espacios.', regex='^\\d{11}$')])),
                ('mail_personal', models.EmailField(db_index=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('profesion', models.CharField(max_length=100)),
                ('tipo_matricula', models.CharField(choices=[('MN', 'Matrícula Nacional (MN)'), ('MP', 'Matrícula Provincial (MP)'), ('NO_APLICA', 'No corresponde (-)')], default='MN', max_length=15)),
                ('numero_matricula', models.CharField(default='-', max_length=30)),
                ('especialidad', models.CharField(blank=True, max_length=120, null=True)),
                ('servicio_area', models.CharField(max_length=120, verbose_name='Servicio / Sala / Área')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('material_enviado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Personal Capacitado',
                'verbose_name_plural': 'Personal Capacitado',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
