# Generated by Django 6.1 on 2026-08-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitado',
            name='acceso_modulos_internacion',
        ),
        migrations.RemoveField(
            model_name='capacitado',
            name='capacitado_internacion',
        ),
        migrations.RemoveField(
            model_name='capacitado',
            name='formulario_capacitacion',
        ),
        migrations.RemoveField(
            model_name='capacitado',
            name='id_agm_solicitado',
        ),
        migrations.RemoveField(
            model_name='capacitado',
            name='servicio_area',
        ),
        migrations.AddField(
            model_name='capacitado',
            name='area_trabajo',
            field=models.CharField(default='-', max_length=150, verbose_name='Área de trabajo (Sala)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitado',
            name='categoria',
            field=models.CharField(choices=[('PLANTA_PERMANENTE', 'Planta permanente'), ('RESIDENTE', 'Residente'), ('CONTRATO', 'Contrato')], default='-', max_length=30, verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitado',
            name='correo_gcba',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo GCBA'),
        ),
        migrations.AddField(
            model_name='capacitado',
            name='dias_horarios',
            field=models.CharField(default='-', max_length=150, verbose_name='Días y Horarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacitado',
            name='otro_hospital_cual',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿En cuál hospital?'),
        ),
        migrations.AddField(
            model_name='capacitado',
            name='servicio',
            field=models.CharField(default='-', max_length=150, verbose_name='Servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='cuil',
            field=models.CharField(max_length=11, unique=True, verbose_name='CUIL'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='especialidad',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Especialidad Acreditada'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='mail_personal',
            field=models.EmailField(max_length=254, verbose_name='Mail Personal'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='numero_matricula',
            field=models.CharField(default='-', max_length=50, verbose_name='Nº de Matrícula'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='otro_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro Apellido'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='otro_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro Nombre'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='permisos_solicitar',
            field=models.CharField(choices=[('HISINT_MEDICO', 'HISINT - PROFESIONAL MEDICO'), ('HISINT_NO_MEDICO', 'HISINT PROFESIONAL NO MEDICO'), ('GDEE_JEFE', 'GDEE-JEFE MESON o DEPARTAMENTO INTGRAL'), ('GDEE_ADMIN', 'GDEE-ADMINISTRATIVO MESON INTGRAL')], max_length=40, verbose_name='Permisos a solicitar'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='profesion',
            field=models.CharField(max_length=120, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Personal'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='tipo_matricula',
            field=models.CharField(choices=[('NACIONAL', 'Matrícula Nacional (MN) [Prioritaria]'), ('PROVINCIAL', 'Matrícula Provincial (MP)'), ('OTRA', 'Otra Matrícula'), ('NO_CORRESPONDE', 'No corresponde (-)')], default='NACIONAL', max_length=20, verbose_name='Tipo de Matrícula'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='tipo_usuario',
            field=models.CharField(choices=[('MEDICO', 'Médico/a'), ('NO_MEDICO', 'Profesional de salud No médico'), ('ADMINISTRATIVO', 'Administrativo/a'), ('JEFE_ADMINISTRATIVO', 'Jefe administrativo')], max_length=30, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterModelTable(
            name='capacitado',
            table='capacitados',
        ),
    ]
