# Generated by Django 6.1 on 2026-09-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0003_remove_capacitado_otro_hospital_cual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitado',
            name='area_trabajo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Área de trabajo (Sala)'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='categoria',
            field=models.CharField(blank=True, choices=[('PLANTA_PERMANENTE', 'Planta permanente'), ('RESIDENTE', 'Residente'), ('CONTRATO', 'Contrato')], max_length=30, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='dias_horarios',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Días y Horarios'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='numero_matricula',
            field=models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Nº de Matrícula'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='permisos_solicitar',
            field=models.CharField(choices=[('HISINT_MEDICO', 'HISINT - PROFESIONAL MEDICO'), ('HISINT_NO_MEDICO', 'HISINT PROFESIONAL NO MEDICO'), ('GDEE_JEFE', 'GDEE-JEFE MESON o DEPARTAMENTO INTGRAL'), ('GDEE_ADMIN', 'GDEE-ADMINISTRATIVO MESON INTGRAL')], max_length=40, verbose_name='Permisos a solicitar'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='profesion',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='telefono',
            field=models.CharField(default='-', max_length=50, verbose_name='Teléfono Personal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='tipo_matricula',
            field=models.CharField(blank=True, choices=[('NACIONAL', 'Matrícula Nacional (MN) [Prioritaria]'), ('PROVINCIAL', 'Matrícula Provincial (MP)'), ('OTRA', 'Otra Matrícula'), ('NO_CORRESPONDE', 'No corresponde (-)')], max_length=20, null=True, verbose_name='Tipo de Matrícula'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('MEDICO', 'Médico/a'), ('NO_MEDICO', 'Profesional de salud No médico'), ('ADMINISTRATIVO', 'Administrativo/a'), ('JEFE_ADMINISTRATIVO', 'Jefe administrativo')], max_length=30, null=True, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='capacitado',
            name='trabaja_otro_hospital',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Hospital General de Agudos Dr. T. Álvarez', 'Hospital General de Agudos Dr. T. Álvarez'), ('Hospital General de Agudos Dr. C. Argerich', 'Hospital General de Agudos Dr. C. Argerich'), ('Hospital General de Agudos Dr. C. Durand', 'Hospital General de Agudos Dr. C. Durand'), ('Hospital General de Agudos Dr. J. A. Fernández', 'Hospital General de Agudos Dr. J. A. Fernández'), ('Hospital General de Agudos Dra. Cecilia Grierson', 'Hospital General de Agudos Dra. Cecilia Grierson'), ('Hospital General de Agudos J. M. Penna', 'Hospital General de Agudos J. M. Penna'), ('Hospital General de Agudos P. Piñero', 'Hospital General de Agudos P. Piñero'), ('Hospital General de Agudos Dr. I. Pirovano', 'Hospital General de Agudos Dr. I. Pirovano'), ('Hospital General de Agudos J. M. Ramos Mejía', 'Hospital General de Agudos J. M. Ramos Mejía'), ('Hospital General de Agudos B. Rivadavia', 'Hospital General de Agudos B. Rivadavia'), ('Hospital General de Agudos Donación F. Santojanni', 'Hospital General de Agudos Donación F. Santojanni'), ('Hospital General de Agudos Dr. E. Tornú', 'Hospital General de Agudos Dr. E. Tornú'), ('Hospital General de Agudos D. Vélez Sarsfield', 'Hospital General de Agudos D. Vélez Sarsfield'), ('Hospital General de Agudos A. Zubizarreta', 'Hospital General de Agudos A. Zubizarreta'), ('Hospital General de Niños Pedro de Elizalde', 'Hospital General de Niños Pedro de Elizalde'), ('Hospital General de Niños Ricardo Gutiérrez', 'Hospital General de Niños Ricardo Gutiérrez'), ('Hospital de Emergencias Psiquiátricas Torcuato de Alvear', 'Hospital de Emergencias Psiquiátricas Torcuato de Alvear'), ('Hospital de Salud Mental Braulio Moyano', 'Hospital de Salud Mental Braulio Moyano'), ('Hospital de Salud Mental J. T. Borda', 'Hospital de Salud Mental J. T. Borda'), ('Hospital Infanto Juvenil C. Tobar García', 'Hospital Infanto Juvenil C. Tobar García'), ('Hospital de Odontología José Dueñas', 'Hospital de Odontología José Dueñas'), ('Hospital de Odontología Dr. Ramón Carrillo (ex nacional)', 'Hospital de Odontología Dr. Ramón Carrillo (ex nacional)'), ('Hospital de Odontología Infantil Don Benito Quinquela Martín', 'Hospital de Odontología Infantil Don Benito Quinquela Martín'), ('Hospital de Oftalmología Santa Lucía', 'Hospital de Oftalmología Santa Lucía'), ('Hospital Oftalmológico Dr. Pedro Lagleyze', 'Hospital Oftalmológico Dr. Pedro Lagleyze'), ('Hospital de Gastroenterología B. Udaondo', 'Hospital de Gastroenterología B. Udaondo'), ('Hospital Municipal de Oncología María Curie', 'Hospital Municipal de Oncología María Curie'), ('Hospital de Rehabilitación Respiratoria M. Ferrer', 'Hospital de Rehabilitación Respiratoria M. Ferrer'), ('Hospital de Infecciosas F. Muñiz', 'Hospital de Infecciosas F. Muñiz'), ('Instituto de Zoonosis L. Pasteur', 'Instituto de Zoonosis L. Pasteur'), ('Instituto de Rehabilitación Psicofísica ( I.R.E.P. )', 'Instituto de Rehabilitación Psicofísica ( I.R.E.P. )'), ('Hospital de Quemados Dr. Arturo Umberto Illia', 'Hospital de Quemados Dr. Arturo Umberto Illia'), ('Hospital de Rehabilitación M. Rocca', 'Hospital de Rehabilitación M. Rocca'), ('Hospital Materno Infantil R. Sardá', 'Hospital Materno Infantil R. Sardá')], default='No', max_length=150, null=True, verbose_name='Trabaja en otro hospital? (Cuál?)'),
        ),
    ]
